# To run production: docker-compose up --build -d
version: "3.4"
services:
  abet_docker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8800:80
      - 8800:443
    volumes:
      - /certs/abet:/certs